# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - test.mockup
        - demo

platforms:
  - name: bento/debian-8.4

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        demo.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - demo

